# Используем официальный образ Airflow
FROM apache/airflow:2.8.1



RUN apt-get update && \
    apt-get install -y tesseract-ocr tesseract-ocr-rus libtesseract-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /requirements.txt

RUN pip install --upgrade pip
RUN pip install --no-cache-dir --user -r /requirements.txt
