FROM apache/airflow:2.8.1

USER root

RUN apt-get update && \
    apt-get install -y \
        tesseract-ocr \
        tesseract-ocr-rus \
        libtesseract-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


USER airflow

COPY requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt
